driver733/kotlin-vs-java

- code/java/collections/04.java
Fixes https://github.com/driver733/kotlin-vs-java/pull/6
> partitionedBy java code fixed

- code/java/io/read-file-to-string.java
> read-file-to-string updated to java 11

- code/kotlin/basic/variables-i.kt
- code/kotlin/basic/variables-ii.kt
Fixes https://github.com/driver733/kotlin-vs-java/issues/12
> variables-II refactoring

- code/java/basic/default-parameters.java
- code/java/basic/elvis-operator.java
- code/java/basic/hello-world.java
- code/java/basic/null-i.java
- code/java/basic/operations.java
- code/java/basic/read-file.java
- code/java/basic/switch.java
- code/java/classes/classes-06.java
- code/java/collections/01.java
- code/java/collections/03.java
- code/java/collections/08.java
- code/java/concurrency/01.java
- code/java/dsl/01.java
- code/java/dsl/03.java
- code/java/scoping-functions/apply.java
- code/java/scoping-functions/let-apply.java
- code/java/scoping-functions/run.java
- code/java/scoping-functions/takeIf.java
- code/java/scoping-functions/with.java
> various examples improvements

- cirru/footer.cirru
- cirru/header.cirru
- code/java/basic/variables-i.java
- css/style.css
> lang version is now specified in the footer

- code/java/basic/cast.java
- code/java/basic/elvis-operator.java
- code/java/basic/null-ii.java
- code/java/basic/operations.java
- code/java/basic/strings-i.java
- code/java/basic/strings-ii.java
- code/java/basic/ternary-operator.java
- code/java/classes/classes-00.java
- code/java/classes/classes-09.java
- code/java/collections/01.java
- code/java/collections/03.java
- code/java/collections/04.java
- code/java/collections/05.java
- code/java/collections/06.java
- code/java/collections/07.java
- code/java/collections/08.java
- code/java/concurrency/03.java
- code/java/dsl/01.java
- code/java/dsl/03.java
- code/java/functions/functions-09.java
- code/java/scoping-functions/also.java
- code/java/scoping-functions/apply.java
- code/java/scoping-functions/let-apply.java
- code/java/scoping-functions/let.java
- code/java/scoping-functions/run.java
- code/java/scoping-functions/takeIf.java
- code/java/scoping-functions/with.java
> updated java code to java 13

- cirru/collections.cirru
- code/java/collections/collecting-and-then.java
- code/kotlin/collections/collecting-and-then.kt
> CollectingAndThen example added

- code/java/concurrency/01.java
- code/java/concurrency/02.java
- code/java/concurrency/03.java
- code/java/spring-framework/spring-framework-00.java
- code/kotlin/concurrency/02.kt
- code/kotlin/concurrency/03.kt
- code/kotlin/delegated-properties/map.kt
- code/kotlin/spring-framework/spring-framework-00.kt
> generics formatting fixed

- make.coffee
> html generation fix

- .circleci/config.yml
- .gitignore
- README.md
- package.json
> circleci fix

- code/kotlin/basic/hello-world.kt
> hello world upd

- code/kotlin/collections/05.kt
> Collections sort fix

- cirru/collections.cirru
- code/java/collections/09_CollectionsInfixFunctions.java
- code/kotlin/collections/09_CollectionsInfixFunctions.kt
> Collections infix functions

- cirru/collections.cirru
- code/java/collections/13_Comparators.java
- code/kotlin/collections/13_Comparators.kt
> #66 - comparators added

- cirru/index.cirru
- code/java/basic/arrays.java
- code/kotlin/basic/arrays.kt
> #64 - arrays added

- code/java/scoping-functions/let.java
Just going through and I noticed a typo.
> Fix typo in 'final'

- code/java/collections/02_Filter.java
- code/kotlin/collections/02_Filter.kt
- code/kotlin/collections/13_Comparators.kt
> refactoring

- code/java/basic/use.java
- code/kotlin/basic/use.kt
> "use" example added

- css/style.css
> #85 - css fix added

- css/style.css
> #89 - completed

- cirru/error-prone.cirru
- cirru/header.cirru
- code/java/error-prone/01-equals.java
- code/kotlin/error-prone/01-equals.kt
> #91 - completed

- code/java/concurrency/01.java
- code/java/concurrency/02.java
- code/kotlin/concurrency/01.kt
> #93 - completed

- code/java/concurrency/01.java
> #95 - completed

- css/style.css
> #97 - completed

- code/kotlin/collections/10_CollectingAndThen.kt
> #99 - refactoring
